version: '3.4'

services:
  naming-server:
    image: rafaelsilva2001/naming-server:0.0.1-SNAPSHOT
    ports:
      - 8761:8761
    networks:
     - rafael-network

  zipkin-server:
    image: openzipkin/zipkin:2.23.2
    ports:
       - 9411:9411
    depends_on:
       - rabbit-mq
    environment:
      RABBIT_URI: amqp://guest:guest@rabbit-mq:5672
    networks:
        - rafael-network

  rabbit-mq:
    image: rabbitmq:3.8.14-management
    ports:
       - 5672:5672
       - 15672:15672
    networks:
     - rafael-network    
  
  api-gateway:
    image: rafaelsilva2001/api-gateway:0.0.1-SNAPSHOT
    ports:
       - 8765:8765
    depends_on:
      - naming-server
      - rabbit-mq
    environment:
       EUREKA.CLIENT.SERVICEURL.DEFAULTZONE: http://naming-server:8761/eureka
       SPRING.ZIPKIN.BASEURL: http://zipkin-server:9411/
       RABBIT_URI: amqp://guest:guest@rabbit-mq:5672
       SPRING_RABBITMQ_HOST: rabbit-mq
       SPRING_ZIPKIN_SENDER_TYPE: rabbit
    networks:
     - rafael-network        
  cambio-db:
    image: mysql:5.7.22
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    ports:
       - 3308:3308
    expose:
     - 3308
    environment:
       TZ: America/Sao_Paulo
       MYSQL_ROOT_PASSWORD: admin
       MYSQL_USER: docker
       MYSQL_PASSWORD: admin
       MYSQL_DATABASE: cambio_service
       MTSQL_ROOT_HOST: '%'
       MYSQL_TCP_PORT: 3308
    networks:
     - rafael-network        


  cambio-service:
      image: 	rafaelsilva2001/cambio-service
      restart: always
      build:
         context: .
         dockerfile: cambio-service/Dockerfile
      ports:
         - 8000:8000
      environment:
          TZ: America/Sao_Paulo
          EUREKA.CLIENT.SERVICEURL.DEFAULTZONE: http://naming-server:8761/eureka
          SPRING.ZIPKIN.BASEURL: http://zipkin-server:9411/
          SPRING.DATASOURCE.URL: jdbc:mysql://cambio-db:3308/cambio_service?useSSL=false&serverTimezone=UTC&enabledTLSProtocols=TLSv1.2
          SPRING.DATASOURCE.USERNAME: root
          SPRING.DATASOURCE.PASSWORD: admin
          SPRING.FLYWAY.URL: jdbc:mysql://cambio-db:3308/cambio_service?useSSL=false&serverTimezone=UTC&enabledTLSProtocols=TLSv1.2
          SPRING.FLYWAY.USER: root
          SPRING.FLYWAY.PASSWORD: admin
          RABBIT_URI: amqp://guest:guest@rabbit-mq:5672
          SPRING_RABBITMQ_HOST: rabbit-mq
          SPRING_ZIPKIN_SENDER_TYPE: rabbit
      depends_on:
         - naming-server
         - cambio-db
         - rabbit-mq
      networks:
       - rafael-network       

  book-service:
      image: 	rafaelsilva2001/book-service
      restart: always
      build:
         context: .
         dockerfile: book-service/Dockerfile
      ports:
         - 8100:8100
      environment:
          TZ: America/Sao_Paulo
          EUREKA.CLIENT.SERVICEURL.DEFAULTZONE: http://naming-server:8761/eureka
          SPRING.ZIPKIN.BASEURL: http://zipkin-server:9411/
          SPRING.DATASOURCE.URL: jdbc:mysql://book-db:3310/book_service?useSSL=false&serverTimezone=UTC&enabledTLSProtocols=TLSv1.2
          SPRING.DATASOURCE.USERNAME: root
          SPRING.DATASOURCE.PASSWORD: admin
          SPRING.FLYWAY.URL: jdbc:mysql://book-db:3310/book_service?useSSL=false&serverTimezone=UTC&enabledTLSProtocols=TLSv1.2
          SPRING.FLYWAY.USER: root
          SPRING.FLYWAY.PASSWORD: admin
          RABBIT_URI: amqp://guest:guest@rabbit-mq:5672
          SPRING_RABBITMQ_HOST: rabbit-mq
          SPRING_ZIPKIN_SENDER_TYPE: rabbit
      depends_on:
         - naming-server
         - book-db
         - rabbit-mq
      networks:
       - rafael-network       

  book-db:
     image: mysql:5.7.22
     command: --default-authentication-plugin=mysql_native_password
     restart: always
     ports:
        - 3310:3310
     expose:
      - 3310
     environment:
        TZ: America/Sao_Paulo
        MYSQL_ROOT_PASSWORD: admin
        MYSQL_USER: docker
        MYSQL_PASSWORD: admin
        MYSQL_DATABASE: book_service
        MTSQL_ROOT_HOST: '%'
        MYSQL_TCP_PORT: 3310
     networks:
      - rafael-network        
networks:
  rafael-network:
    driver: bridge